apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-south-1

vpc:
  id: vpc-0570dc181597c47d0
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0e8be696b52c9437b
      my-new-stack-PublicSubnet02:
        id: subnet-0ef5ac4e4f8881c20
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-0f44e20d9f22e2cac
      my-new-stack-PrivateSubnet02:
        id: subnet-04a9dc1b3f7c0fa6d

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
